import Head from 'next/head' 
import About from '../components/about'
import Contact from '../components/contact'
import Main from '../components/main'
import Projects from '../components/projects'
import Skills from '../components/skills'

export default function Home() {
  return (
    <div> 
        <Head>
          <title>Client | Front-End Developer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Main />
        <About />
        <Skills /> 
        <Projects />
        <Contact />
 
    </div>
  )
}
